def hamming(s1, s2):
    l = len(s1)
    return sum([s1[k] != s2[k] for k in range(l)])

def closest(strings):
    dist = {k: [] for k in strings}
    n = len(strings)
    for i in range(n):
        for j in range(n):
            dist[strings[i]].append(hamming(strings[i], strings[j]))

    min_dist = 10000000
    closest_string = ''
    for i in range(n):
        if min_dist > sum(dist[strings[i]]):
            min_dist = sum(dist[strings[i]])
            closest = list(dist.keys())[i]

    return closest

print(closest(['ATCAATATCAA', 'ATTAAATAACT', 'AATCCTTAAAC', 'CTACTTTCTTT', 'TCCCATCCTTT', 'ACTTCAATATA']))
print(closest(['CTCCATCACAC', 'AATATCTACAT', 'ACATTCTCCAT', 'CCTCCCCACTC']))
print(closest(['AACACCCTATA', 'CTTCATCCACA', 'TTTCAATTTTC', 'ACAATCAAACC', 'ATTCTACAACT', 'ATTCCTTATTC', 'ACTTCTCTATT', 'TAAAACTCACC', 'CTTTTCCCACC', 'ACCTTTTCTCA', 'TACCACTACTT']))
print(closest(['ACAAAATCCTATCAAAAACTACCATACCAAT', 'ACTATACTTCTAATATCATTCATTACACTTT', 'TTAACTCCCATTATATATTATTAATTTACCC', 'CCAACATACTAAACTTATTTTTTAACTACCA', 'TTCTAAACATTACTCCTACACCTACATACCT', 'ATCATCAATTACCTAATAATTCCCAATTTAT', 'TCCCTAATCATACCATTTTACACTCAAAAAC', 'AATTCAAACTTTACACACCCCTCTCATCATC', 'CTCCATCTTATCATATAATAAACCAAATTTA', 'AAAAATCCATCATTTTTTAATTCCATTCCTT', 'CCACTCCAAACACAAAATTATTACAATAACA', 'ATATTTACTCACACAAACAATTACCATCACA', 'TTCAAATACAAATCTCAAAATCACCTTATTT', 'TCCTTTAACAACTTCCCTTATCTATCTATTC', 'CATCCATCCCAAAACTCTCACACATAACAAC', 'ATTACTTATACAAAATAACTACTCCCCAATA', 'TATATTTTAACCACTTACCAAAATCTCTACT', 'TCTTTTATATCCATAAATCCAACAACTCCTA', 'CTCTCAAACATATATTTCTATAACTCTTATC', 'ACAAATAATAAAACATCCATTTCATTCATAA', 'CACCACCAAACCTTATAATCCCCAACCACAC']))
